version: '3.1'

services:

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 8081:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
